-- CPHub V4 — Rollback migration 001
DROP TABLE IF EXISTS user_settings CASCADE;
DROP TABLE IF EXISTS snippets CASCADE;
DROP TABLE IF EXISTS external_submissions CASCADE;
DROP TABLE IF EXISTS local_submissions CASCADE;
DROP TABLE IF EXISTS problem_logs CASCADE;
DROP TABLE IF EXISTS test_cases CASCADE;
DROP TABLE IF EXISTS problems CASCADE;
DROP TABLE IF EXISTS linked_accounts CASCADE;
DROP TABLE IF EXISTS users CASCADE;
