/var/log/cphub/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0644 cphub cphub
}

/opt/cphub/apps/api/logs/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
}
